# Generated by Django 4.0.1 on 2022-01-24 03:42

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short', models.SlugField(blank=True, help_text='the part of URL after / that will redirect to the long URL, e.g. https://my.short.link/[slug]', max_length=64, unique=True, verbose_name='short link slug')),
                ('long', models.URLField(max_length=512, verbose_name='long URL')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last update')),
                ('is_working', models.BooleanField(verbose_name='URL is working')),
                ('last_check', models.DateTimeField(verbose_name='last time URL was checked')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
        ),
    ]
