# Generated by Django 4.0.1 on 2022-01-25 00:13

from django.db import migrations, models
import qlinks.models


class Migration(migrations.Migration):

    dependencies = [
        ('qlinks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='next_check',
            field=models.DateTimeField(db_index=True, default=qlinks.models.compute_next_check, verbose_name='the next time the URL will be checked'),
        ),
    ]
